---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudflare-session-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloudflare-session-operator-manager-role
subjects:
  - kind: ServiceAccount
    name: cloudflare-session-operator
    namespace: system
