{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "hello-world.fullname" . }}-db
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind | default "SecretStore" }}
  target:
    name: {{ include "hello-world.fullname" . }}-db
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        url: {{ printf "{{ .database_url }}" | quote }}
  dataFrom:
    - extract:
        key: {{ .Values.externalSecret.secretPath }}
{{- end }}
