{{- if not .Values.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hello-world.fullname" . }}-db
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
type: Opaque
stringData: {}
  # Example: provide DATABASE_URL when not using ExternalSecret
  # url: "postgres://user:password@postgres-host:5432/hello_world?sslmode=require"
{{- end }}
