{{- if .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "hello-world.secretStoreName" . }}
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secretStore.region | default "eu-central-1" }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "hello-world.serviceAccountName" . }}
{{- end }}
